export { default as LoginScreen } from './LoginScreen/LoginScreen'
export { default as HomeScreen } from './HomeScreen/HomeScreen'
export { default as RegistrationScreen } from './RegistrationScreen/RegistrationScreen'
export { default as DataHistory } from './DataHistory/DataHistory'
export { default as Profile } from './Profile/Profile'
export { default as Settings } from './Settings/Settings'
export { default as EditInfo } from './Settings/EditInfo/EditInfo'
export { default as SensorConfig } from './Settings/SensorConfig/SensorConfig'